fix wget issues

diff --git a/backup_new b/backup_new
--- a/backup_new
+++ b/backup_new
@@ -74,15 +74,15 @@ SCRIPT_DEST=/usr/local/bin/$SCRIPT_NAME
 
 # Checking for update
 
-sha=$(wget https://api.github.com/repos/${GITHUB_REPO}/git/refs -O - -q | sed -n '/sha/ s|.*: "\(.*\)",|\1|p' )
-git_sha=$( wget https://api.github.com/repos/${GITHUB_REPO}/git/trees/${sha} -O - -q | grep -A 5 "\"path\": \"${SCRIPT_NAME}\","|sed -n '/sha/ s|.*: "\(.*\)",|\1|p' )
+sha=$( curl -sS https://api.github.com/repos/${GITHUB_REPO}/git/refs | sed -n '/sha/ s|.*: "\(.*\)",|\1|p' )
+git_sha=$( curl -sS https://api.github.com/repos/${GITHUB_REPO}/git/trees/${sha} | grep -A 5 "\"path\": \"${SCRIPT_NAME}\","|sed -n '/sha/ s|.*: "\(.*\)",|\1|p' )
 file_sha=$( (echo -ne "blob `stat -c %s ${SCRIPT_DEST}`\0"; cat ${SCRIPT_DEST}) | sha1sum | awk '{print $1}' )
 
 if [ ${git_sha} != ${file_sha} ]; then
     echo "Update available"
     TMPDIR=$(mktemp -d -t $SCRIPT_NAME.XXXXXX)
     cd $TMPDIR
-    wget -q "$SCRIPT_URI" -O "$SCRIPT_NAME" || { echo "Error downloading updated script"; return; }
+    curl -sS "$SCRIPT_URI" -o "$SCRIPT_NAME" || { echo "Error downloading updated script"; return; }
     if [[ -w $SCRIPT_DEST || -w $(dirname $SCRIPT_DEST) ]]; then
       echo "Updating with new version"
       mv $SCRIPT_DEST /tmp/
